### ISSUE TITLE
Add wiki screenshots

### ISSUE THREAD

**Issue by caw742** [EasternEdgeRobotics/2016#241]
I hear that if I can host images here for the wiki. So here are some screenshots:

<img width="1440" alt="screen shot 2016-10-15 at 4 18 38 pm" src="https://cloud.githubusercontent.com/assets/10786351/19413125/a10c83c2-92ff-11e6-9af2-d510f7551b29.png">
<img width="697" alt="screen shot 2016-10-15 at 4 24 03 pm" src="https://cloud.githubusercontent.com/assets/10786351/19413130/a1105218-92ff-11e6-9584-8edd03c42aed.png">
<img width="1440" alt="screen shot 2016-10-15 at 4 48 27 pm" src="https://cloud.githubusercontent.com/assets/10786351/19413126/a10e7736-92ff-11e6-8c07-d786e32ef47a.png">
<img width="1440" alt="screen shot 2016-10-15 at 4 58 46 pm" src="https://cloud.githubusercontent.com/assets/10786351/19413127/a10ec664-92ff-11e6-8eb9-f2f260566188.png">
<img width="1440" alt="screen shot 2016-10-15 at 5 00 52 pm" src="https://cloud.githubusercontent.com/assets/10786351/19413129/a10f73ac-92ff-11e6-87cb-af8f84bbaf6b.png">
<img width="1440" alt="screen shot 2016-10-15 at 5 23 10 pm" src="https://cloud.githubusercontent.com/assets/10786351/19413128/a10eee32-92ff-11e6-80cf-6d098e3b4038.png">
<img width="1440" alt="screen shot 2016-10-15 at 5 25 02 pm" src="https://cloud.githubusercontent.com/assets/10786351/19413131/a11969f2-92ff-11e6-9948-37ab8f62df08.png">

**Comment by cal-pratt** [comment]
You can actually just paste images from the clipboard into github issues. ie `PrtScrn, ctrl+v`
You don't even need to upload the post, you can just take the url it creates and pop it directly into the readme/ wiki

**Comment by caw742** [comment]
Good to know.

Fun fact: While finding this hack I accidentally lost all of my text for the walkthrough 🙃

**Comment by cal-pratt** [comment]
haha nice. Also if a dev wants to auto-create `eclipse` or `intellij` projects you can add the following to `2016/build.gradle`

    apply plugin: 'idea'
    apply plugin: 'eclispe'

Then build the project files by calling either `gradle idea` or  `gradle eclipse`

**Comment by caw742** [comment]
Right, just like they do at Nokia. My current solution is using the gradle plugin in eclipse and adding gradle nature to the project. I should add that to provide options tho

**Comment by cal-pratt** [comment]
Agreed. Should make on-boarding a bit easier!
