### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by cal-pratt** [EasternEdgeRobotics/2016#243]
The `EasternEdgeRobotics/2016` project name no longer makes a lot of sense. `ControlSoftware` is already taken by the old `C#` project, and `2017` is kind of a lame name. 

Lets think of some good names @EasternEdgeRobotics/developers !

**Comment by Stephenchislett** [comment]
I suggest ControlSoftware: Tokyo Drift

**Comment by caw742** [comment]
@Stephenchislett I like your style. I'll keep that going by suggesting 2 Control 2 Software.

Additionally I'd like to suggest 2016 2: Electric Boogaloo

**Comment by cal-pratt** [comment]
Liking these suggestions so far lol

**Comment by hgm375** [comment]
Control Software 2: Control Harder
Or also: Still Control Software

**Comment by caw742** [comment]
As good as these suggestions are, went with 2017
